---
title: "xmsannotator-introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{xmsannotator-introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Example 1: run a feature table with HMDB
```{r setup}
library(xMSannotator)

#read sample data
testdata <- read.csv(system.file(
  "extdata",
  "example_data_table.csv",
  package = "xMSannotator"
))

#call multilevelannotation function
system.time(res <- multilevelannotation(testdata,max.mz.diff=10,max.rt.diff = 10,corthresh=0.7,mode="pos",db_name = "HMDB",clustmethod = "auto",outloc="~/xMSannotatoroutv1.4/"))

#returns a list with stage 4 and stage 5 results
print(names(res))

```

## Example 2: run a feature table with HMDB but only for a small set of targeted HMDB IDs
```{r, echo=TRUE}

library(xMSannotator)

###########Parameters to change##############
system.time(annotres4<-multilevelannotation(
  max.mz.diff=10, max.rt.diff=10,corthresh=0.7,
                        dataA=read.csv(system.file("extdata","StdMix_feature_table.csv",package = "xMSannotator")),
                       outloc="~/xMSannotatoroutv1.4custom/", 
                          mode="pos",
                                            clustmethod="auto", 
                                            queryadductlist=c("M+H","M+2H","M+H+NH4","M+ACN+2H","M+2ACN+2H","M+NH4","M+Na","M+ACN+H","M+ACN+Na","M+2ACN+H",
                                                              "2M+H","2M+Na","2M+ACN+H","M+2Na-H","M+H-H2O","M+H-2H2O"),
                                            db_name="HMDB",
                                            customIDs=read.csv(system.file("extdata","StdMix_HMDBIDs.csv",package = "xMSannotator")),
                                            missing.value=0,
                                            filter.by=c("M+H"),
                                             boostIDs=NA,
                                             max_isp=5,
                                            customDB=NA,
                                            peakID_name = "PeakID"
  )
)


```
## Session information

```{r}
sessionInfo()
```
