// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_ultra_annotation_engine
DataFrame run_ultra_annotation_engine(NumericVector data_mz, NumericVector data_time, NumericVector db_mz_R, CharacterVector db_id_R, CharacterVector db_name_R, CharacterVector db_formula_R, NumericVector db_mono_mass_R, CharacterVector db_adduct_R, NumericVector db_adduct_mass_R, CharacterVector query_adducts, double ppm_tol);
RcppExport SEXP _xMSannotator_run_ultra_annotation_engine(SEXP data_mzSEXP, SEXP data_timeSEXP, SEXP db_mz_RSEXP, SEXP db_id_RSEXP, SEXP db_name_RSEXP, SEXP db_formula_RSEXP, SEXP db_mono_mass_RSEXP, SEXP db_adduct_RSEXP, SEXP db_adduct_mass_RSEXP, SEXP query_adductsSEXP, SEXP ppm_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data_mz(data_mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data_time(data_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type db_mz_R(db_mz_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type db_id_R(db_id_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type db_name_R(db_name_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type db_formula_R(db_formula_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type db_mono_mass_R(db_mono_mass_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type db_adduct_R(db_adduct_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type db_adduct_mass_R(db_adduct_mass_RSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type query_adducts(query_adductsSEXP);
    Rcpp::traits::input_parameter< double >::type ppm_tol(ppm_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(run_ultra_annotation_engine(data_mz, data_time, db_mz_R, db_id_R, db_name_R, db_formula_R, db_mono_mass_R, db_adduct_R, db_adduct_mass_R, query_adducts, ppm_tol));
    return rcpp_result_gen;
END_RCPP
}
// build_sparse_graph_parallel
List build_sparse_graph_parallel(NumericMatrix X, NumericVector rt, double rt_window, double alpha);
RcppExport SEXP _xMSannotator_build_sparse_graph_parallel(SEXP XSEXP, SEXP rtSEXP, SEXP rt_windowSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< double >::type rt_window(rt_windowSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(build_sparse_graph_parallel(X, rt, rt_window, alpha));
    return rcpp_result_gen;
END_RCPP
}
// expand_isotopes_ultra_fast_cpp
DataFrame expand_isotopes_ultra_fast_cpp(NumericVector mz, NumericVector time, NumericVector mono_mz, IntegerVector module_id, IntegerVector group_start, IntegerVector group_end, NumericVector isp_mz, NumericVector isp_time, IntegerVector isp_module, CharacterVector formula, double max_diff_rt, int max_isp, double ppm_tol);
RcppExport SEXP _xMSannotator_expand_isotopes_ultra_fast_cpp(SEXP mzSEXP, SEXP timeSEXP, SEXP mono_mzSEXP, SEXP module_idSEXP, SEXP group_startSEXP, SEXP group_endSEXP, SEXP isp_mzSEXP, SEXP isp_timeSEXP, SEXP isp_moduleSEXP, SEXP formulaSEXP, SEXP max_diff_rtSEXP, SEXP max_ispSEXP, SEXP ppm_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mono_mz(mono_mzSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type module_id(module_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_end(group_endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isp_mz(isp_mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isp_time(isp_timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type isp_module(isp_moduleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< double >::type max_diff_rt(max_diff_rtSEXP);
    Rcpp::traits::input_parameter< int >::type max_isp(max_ispSEXP);
    Rcpp::traits::input_parameter< double >::type ppm_tol(ppm_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_isotopes_ultra_fast_cpp(mz, time, mono_mz, module_id, group_start, group_end, isp_mz, isp_time, isp_module, formula, max_diff_rt, max_isp, ppm_tol));
    return rcpp_result_gen;
END_RCPP
}
// stage3_score_engine_cpp
DataFrame stage3_score_engine_cpp(DataFrame DT, DataFrame adduct_weights, CharacterVector primary_adducts, double max_diff_rt, IntegerVector group_start, IntegerVector group_end);
RcppExport SEXP _xMSannotator_stage3_score_engine_cpp(SEXP DTSEXP, SEXP adduct_weightsSEXP, SEXP primary_adductsSEXP, SEXP max_diff_rtSEXP, SEXP group_startSEXP, SEXP group_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type DT(DTSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type adduct_weights(adduct_weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type primary_adducts(primary_adductsSEXP);
    Rcpp::traits::input_parameter< double >::type max_diff_rt(max_diff_rtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_end(group_endSEXP);
    rcpp_result_gen = Rcpp::wrap(stage3_score_engine_cpp(DT, adduct_weights, primary_adducts, max_diff_rt, group_start, group_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xMSannotator_run_ultra_annotation_engine", (DL_FUNC) &_xMSannotator_run_ultra_annotation_engine, 11},
    {"_xMSannotator_build_sparse_graph_parallel", (DL_FUNC) &_xMSannotator_build_sparse_graph_parallel, 4},
    {"_xMSannotator_expand_isotopes_ultra_fast_cpp", (DL_FUNC) &_xMSannotator_expand_isotopes_ultra_fast_cpp, 13},
    {"_xMSannotator_stage3_score_engine_cpp", (DL_FUNC) &_xMSannotator_stage3_score_engine_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_xMSannotator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
