# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ultra_annotation_engine <- function(data_mz, data_time, db_mz_R, db_id_R, db_name_R, db_formula_R, db_mono_mass_R, db_adduct_R, db_adduct_mass_R, query_adducts, ppm_tol) {
    .Call(`_xMSannotator_run_ultra_annotation_engine`, data_mz, data_time, db_mz_R, db_id_R, db_name_R, db_formula_R, db_mono_mass_R, db_adduct_R, db_adduct_mass_R, query_adducts, ppm_tol)
}

build_sparse_graph_parallel <- function(X, rt, rt_window, alpha) {
    .Call(`_xMSannotator_build_sparse_graph_parallel`, X, rt, rt_window, alpha)
}

expand_isotopes_ultra_fast_cpp <- function(mz, time, mono_mz, module_id, group_start, group_end, isp_mz, isp_time, isp_module, formula, max_diff_rt, max_isp, ppm_tol) {
    .Call(`_xMSannotator_expand_isotopes_ultra_fast_cpp`, mz, time, mono_mz, module_id, group_start, group_end, isp_mz, isp_time, isp_module, formula, max_diff_rt, max_isp, ppm_tol)
}

stage3_score_engine_cpp <- function(DT, adduct_weights, primary_adducts, max_diff_rt, group_start, group_end) {
    .Call(`_xMSannotator_stage3_score_engine_cpp`, DT, adduct_weights, primary_adducts, max_diff_rt, group_start, group_end)
}

